export const siteData = [
    {
        image: "/assets/image1.png",
        title: "ELEVATE YOUR TASTE: TODAY'S...",
        location: "Dhaka",
        duration: "3h",
        sector: "Localized Sector",
        rating: 4.8,
        price: 45,

    },
    {
        image: "/assets/image2.png",
        title: "DISCOVER TODAY'S DELICACIES",
        location: "Khulna",
        duration: "1h",
        sector: "Localized Best",
        rating: 4.8,
        price: 20.5,
        
    },
    {
        image: "/assets/image3.png",
        title: "EXCLUSIVE CUISINE OFFERINGS",
        location: "Cumilla",
        duration: "3h",
        sector: "Localized Best",
        rating: 4.8,
        price: 50,
        points: "27+ more points",
    },
    {
        image: "/assets/image4.png",
        title: "A FEAST FOR YOUR SENSES",
        location: "Tangail",
        duration: "1h",
        sector: "Localized Best",
        rating: 4.8,
        price: 25,
    },
    {
        image: "/assets/image5.png",
        title: "TODAY'S GOURMET SELECTION",
        location: "Rangpur",
        duration: "5h",
        sector: "Localized Best",
        rating: 4.8,
        price: 30,
    },
    {
        image: "/assets/image6.png",
        title: "INDULGE IN CHEF'S SPECIALS",
        location: "Cox's",
        duration: "2h",
        sector: "Localized Best",
        rating: 4.8,
        price: 35,
    },
];